name: Pytest

on: [pull_request]

jobs:
  tests:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Unit tests
        run: |
          coverage run -m pytest -m noplaco
          coverage xml
          coverage json
          coverage html
      - name: Archive code coverage html report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: htmlcov
      - name: Get Cover 
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}